### ISSUE TITLE
Fix markdown violations in `README.md`

### ISSUE THREAD

**Issue by RoachxD** [microsoft-farmer/bing-rewards#11]
Hello, I noticed that the `README.md` file has some markdown violations that affect its readability and formatting. I ran the file through a markdown linter and found the following issues:

- Line 3: Inline HTML elements are not recommended for markdown files, as they may not render properly on some platforms. Also, there is a trailing space at the end of the line that should be removed. A possible solution is to replace the `<a>`  tag with markdown syntax for links, and delete the extra space.
- Line 5: Same as line 3, inline HTML elements should be avoided. Replace the `<img>` tag with markdown syntax for images.
- Line 7: There are two consecutive blank lines, which is unnecessary and violates the rule of having only one blank line between paragraphs. Delete one of the blank lines.
- Line 8: Headings should be surrounded by blank lines to improve readability and separate them from other elements. Also, there should be only one top-level heading (`H1`) in a document, and it should be the title of the document. A possible solution is to add a blank line before the heading, and change the heading level to `H2` or lower.
- Line 9: Same as line 3 and 5, inline HTML elements should be avoided. Replace the `<img>` tag with markdown syntax for images.
- Line 11: Same as line 7, there are two consecutive blank lines. Delete one of the blank lines.
- Line 12: Same as line 8, there should be only one top-level heading in a document. Change the heading level to `H2` or lower.
- Line 14: Same as line 3, 5 and 9, inline HTML elements should be avoided. Replace the `<img>` tag with markdown syntax for images.
- Line 19: Same as line 8 and 12, headings should be surrounded by blank lines and there should be only one top-level heading in a document. Add a blank line before the heading, and change the heading level to `H2` or lower.
- Line 20: Same as line 3, 5, 9 and 14, inline HTML elements should be avoided. Replace the `<img>` tag with markdown syntax for images.
- Line 22: Same as line 7 and 11, there are two consecutive blank lines. Delete one of the blank lines.
- Line 25: Same as line 8, 12 and 19, there should be only one top-level heading in a document. Add a blank line before the heading, and change the heading level to `H2` or lower.

**Comment by Pratyay360** [comment]
approved Pr #12
