### ISSUE TITLE
Not working NA/USA 

### ISSUE THREAD

**Issue by seanbperiod** [microsoft-farmer/bing-rewards#22]
As of a few days ago, this has stopped tracking searches for both desktop mobile using any computer/browser on any device. Tried on different connections and locations - not working NA/USA. 

Manual searches continue to work, so it doesn't appear to be a suspension/penalty.  

Any ideas?

**Comment by Pratyay360** [comment]
same for here in India, but I have modified the project to work two days ago isn't it working now ?

**Comment by seanbperiod** [comment]
Pratyay - I just tried your fork and it's working for me now. 🥳
Thanks for the quick response :)

**Comment by Pratyay360** [comment]
Welcome :)
