### ISSUE TITLE
Optimization suggestions for `shuffleArray` and `newTab` functions inside `index.js`.

### ISSUE THREAD

**Issue by RoachxD** [microsoft-farmer/bing-rewards#8]
This issue outlines several micro-optimization suggestions for the `shuffleArray` and `newTab` functions to improve their performance and readability.

In the `shuffleArray` function, it is suggested to replace `var` with `let` and `const` to ensure that the variables are block-scoped. It is also suggested to use destructuring assignment to swap the values of `array[i]` and `array[j]` instead of using a temporary variable.

In the `newTab` function, it is suggested to replace the `used` array with a `Set`, which allows for faster lookup times. It is also suggested to replace the `includes` method with the `has` method, which checks if an element is in the `Set`.

These suggestions can help improve the performance and readability of the code. Please review and let me know if you have any feedback or suggestions.

Thank you! 😊

**Comment by Pratyay360** [comment]
Hi @RoachxD 👋 👋 thanks for your suggestions will definitely consider in future also you can send a pr too. Any kind of contribution is highly appreciated.

**Comment by KSSaiTeja** [comment]
can i work on this issue, i will fix it less than 5 min

**Comment by Pratyay360** [comment]
wait merging
